version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "ci(actions)"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10
    commit-message:
      prefix: "ci(hooks)"
