name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install zsh
      run: sudo apt-get update -qq && sudo apt-get install -y -qq zsh
    - name: Run pre-commit on all files
      run: pipx run pre-commit run --all-files --show-diff-on-failure
